version: '3'
services:
  web:
    build: ./web-app
    ports:
      - "8080:80"
    volumes:
      - ./web-app/config:/config
  init:
    build: ./initcontainer
    volumes:
      - ./web-app/config:/config
